name: Deploy to Server
on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
                - name: Set up Docker Buildx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ github.DOCKER_HUB_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
             docker build . --tag ${{ github.DOCKER_HUB_URL }}/${{ github.repository_owner }}/${{ github.PROJECT_NAME }}:latest
             docker push ${{ github.DOCKER_HUB_URL }}/${{ github.repository_owner }}/${{ github.PROJECT_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code again
        uses: action/checkout@v4
      - name: connect by ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
      - name: deploy to server
        run: |
          docker-compose pull
